// packages/example/src/status/timeUTC.tsx
import React from 'react';
import { useAsyncCache } from 'react-async-cache';

import { getTimeUTC } from './server/getTimeUTC';

export const TimeUTC = () => {
  const { call, response } = useAsyncCache();
  const load = () => {
    call(getTimeUTC);
  }
  React.useEffect(() => { load(); }, []);
  return (
    <div>
      {!response ? <p>Loading...</p> : (
        <p><b>Server time UTC:</b> {response.time} <button onClick={load}>reload</button></p>
      )}
    </div>
  );
}

// packages/example/vue/src-isomor/components/status/TimeUTC.vue
<template>
  <p>TimeUTC</p>
</template>

<script lang="ts">
import {
  Component,
  Vue,
} from "vue-property-decorator";

@Component
export default class TimeUTC extends Vue {}

// import React from 'react';
// import { useAsyncCacheEffect } from 'react-async-cache';

// import { getTimeUTC } from './server/getTimeUTC';

// export const TimeUTC = () => {
//   // this is the same as time.tsx but wrapped inside useAsyncCacheEffect
//   const { load, response } = useAsyncCacheEffect(getTimeUTC);
//   return (
//     <div>
//       {!response ? <p>Loading...</p> : (
//         <p><b>Server time UTC:</b> {response.time} <button onClick={load}>reload</button></p>
//       )}
//     </div>
//   );
// }

</script>
