// packages/isomor-ng-nest/example/uptime.tsx
import React from 'react';
import { getServerUptime } from './server/uptime';
// import { useAsyncCacheEffect } from 'react-async-cache';

export const Uptime = () => {
    const [uptime, setUptime] = React.useState<number>();
    const call = async () => setUptime(await getServerUptime());
    React.useEffect(() => { call(); }, []);
    // or instead of the last 3 lines, use react-async-cache
    // const { response: uptime } = useAsyncCacheEffect(getServerUptime);
    return (
        <p style={{color: 'yellow'}}><b>Server uptime:</b> { uptime || 'loading...' }</p>
    );
};

// packages/isomor-vue-app/example/Uptime.vue
<template>
  <p style="color: green">
    <b>Server uptime:</b>
    {{ uptime || 'loading...' }}
  </p>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { getServerUptime } from "./server/data";

@Component
export default class Uptime extends Vue {
  private uptime!: string;

  data() {
    return {
      uptime: null
    };
  }
  async mounted() {
    this.uptime = await getServerUptime();
  }
}
</script>
