// packages/installer/isomor-react-app/example/uptime.tsx
import React from 'react';
import { getServerUptime } from './server/uptime';

export const Uptime = () => {
    const [uptime, setUptime] = React.useState<number>();
    React.useEffect(() => { getServerUptime().then(setUptime); }, []);
    return (
        <p style={{color: 'yellow'}}><b>Server uptime:</b> { uptime || 'loading...' }</p>
    );
};

// packages/isomor-vue-app/example/Uptime.vue
<template>
  <p style="color: green">
    <b>Server uptime:</b>
    {{ uptime || 'loading...' }}
  </p>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { getServerUptime } from "./server/data";

@Component
export default class Uptime extends Vue {
  private uptime!: string;

  data() {
    return {
      uptime: null
    };
  }
  async mounted() {
    this.uptime = await getServerUptime();
  }
}
</script>
