// packages/example/vue/src-isomor/App.vue
<template>
  <div id="app">
    <h1>Isomor Vue example</h1>
    <ul id="example-1">
      <li v-for="item in list">
        {{ item }}
      </li>
    </ul>
    <button @click="load()">load</button>
    <TwoColumn />
    <Stats />
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import TwoColumn from "./components/TwoColumn.vue";
import Stats from "./components/status/Stats.vue";
import { getList } from "./server/data";

@Component({
  components: {
    TwoColumn,
    Stats,
  }
})
export default class App extends Vue {
  private list!: string[];

  async load() {
    this.list = await getList({ foo: "bar" });
  }

  data() {
    return {
      list: null
    };
  }
  mounted() {
    this.load();
  }
}
</script>

<style>
#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
}
</style>

// packages/example/src/App.tsx
import React, { Component } from 'react';
import './App.css';

import { getList } from './server/data';
import { GetListInput } from './server/getList.input';
import { Stats } from './status/stats';

class App extends Component {
  state = {
    list: []
  };

  async componentDidMount() {
    await this.onRemoteLoad();
  }

  onRemoteLoad = async () => {
    const input: GetListInput = { foo: 'magic' };
    const list = await getList(input);
    this.setState({ list });
  }

  render() {
    return (
      <div className="App">
        <header className="App-header">
          Isomor
        </header>
        <ul>
          {
            this.state.list.map((item, index) => <li key={index}>{item}</li>)
          }
        </ul>
        <button onClick={this.onRemoteLoad}>load again</button>
        <Stats />
      </div>
    );
  }
}

// // Functional example
// const App2 = () => {
//   const [list, setList] = React.useState<string[]>([]);
//   const load = async () => {
//     const input: GetListInput = { foo: 'magic' };
//     setList(await getList(input));
//   }
//   React.useEffect(() => { load(); }, []);
//   return (
//     <div className="App">
//       <header className="App-header">
//         Isomor
//     </header>
//       <ul>
//         {
//           list.map((item, index) => <li key={index}>{item}</li>)
//         }
//       </ul>
//       <button onClick={load}>load again</button>
//       <Stats />
//     </div>
//   );
// }

export default App;
