// packages/example/src/status/time.tsx
import React from 'react';
import { getTime } from './server/getTime';
import { useIsomor } from '../Isomor';

export const Time = () => {
  const { call, response } = useIsomor();
  const load = () => {
    call(getTime);
  }
  React.useEffect(() => { load(); }, []);
  return (
    <div>
      {!response ? <p>Loading...</p> : (
        <p><b>Server time:</b> {response.time} <button onClick={load}>reload</button></p>
      )}
    </div>
  );
}

// packages/example/vue/src/components/status/Time.vue
<template>
    <p v-if="response">
        <b>Server time:</b> {{response.time}} <button @click="load()">reload</button>
    </p>
    <p v-else>Loading...</p>
</template>

<script lang="ts">
import {
  Component,
  Vue,
} from "vue-property-decorator";
import { useAsyncCacheWatch } from "vue-async-cache";
import { getTime } from "./server/getTime";

@Component
export default class Time extends Vue {
  private cacheWatch = useAsyncCacheWatch(getTime);

  get response() {
    return this.cacheWatch.getResponse();
  }

  load() {
    this.cacheWatch.call();
  }

  async mounted() {
      this.load();
  }
}
</script>
