// packages/example/src-isomor/App.tsx
import React, { Component } from 'react';
import './App.css';

import { getList } from './server/data';
import { GetListInput } from './server/getList.input';
import { Stats } from './status/stats';
import { TwoColumn } from './TwoColumn';
import { Auth } from './auth/auth';
import { ErrorExample } from './error/ErrorExample';
import { ErrorExample2 } from './error/ErrorExample2';

const App = () => {
  const [list, setList] = React.useState<string[]>([]);
  const load = async () => {
      const input: GetListInput = { foo: 'magic' };
      setList(await getList(input));
  }
  React.useEffect(() => { load(); }, []);
  return (
      <div className="App">
          <header className="App-header">
            Isomor <Auth />
          </header>
          <div className="App-content">
            <ul>
              {
                list.map((item, index) => <li key={index}>{item}</li>)
              }
            </ul>
            <button onClick={load}>load again</button>
            <TwoColumn />
            <Stats />
            <ErrorExample />
            <ErrorExample2 />
          </div>
      </div>
  );
}

export default App;

// class App extends Component {
//   state = {
//     list: []
//   };

//   async componentDidMount() {
//     await this.onRemoteLoad();
//   }

//   onRemoteLoad = async () => {
//     const input: GetListInput = { foo: 'magic' };
//     const list = await getList(input);
//     this.setState({ list });
//   }

//   render() {
//     return (
//       <div className="App">
//         <header className="App-header">
//           Isomor
//           <Time />
//         </header>
//         <Stats />
//         <Time />
//         <hr />
//         <ul>
//           {
//             this.state.list.map((item, index) => <li key={index}>{item}</li>)
//           }
//         </ul>
//         <button onClick={this.onRemoteLoad}>load again</button>
//       </div>
//     );
//   }
// }

// packages/example/vue/src-isomor/App.vue
<template>
  <div id="app">
    <h1>Isomor Vue example</h1>
    <ul id="example-1">
      <li v-for="item in list">
        {{ item }}
      </li>
    </ul>
    <button @click="load()">load</button>
    <TwoColumn />
    <Stats />
    <ErrorExample />
    <ErrorExample2 />
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import TwoColumn from "./components/TwoColumn.vue";
import Stats from "./components/status/Stats.vue";
import ErrorExample from "./components/error/ErrorExample.vue";
import ErrorExample2 from "./components/error/ErrorExample2.vue";
import { getList } from "./server/data";

@Component({
  components: {
    TwoColumn,
    Stats,
    ErrorExample,
    ErrorExample2,
  }
})
export default class App extends Vue {
  private list!: string[];

  async load() {
    this.list = await getList({ foo: "bar" });
  }

  data() {
    return {
      list: null
    };
  }
  mounted() {
    this.load();
  }
}
</script>

<style>
#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
}
</style>
