// packages/example/vue/src/components/color/Color.vue
<template>
  <p>Color</p>
</template>

<script lang="ts">
import {
  Component,
  Vue,
} from "vue-property-decorator";

@Component
export default class Color extends Vue {}

// import React from 'react';
// import { useAsyncCacheWatch } from 'react-async-cache';
// import { getColor, setColor } from './server/color';

// export const Color = () => {
//     const { load, response: color, update } = useAsyncCacheWatch(getColor);
//     React.useEffect(() => { load(); }, []);
//     const onClickColor = (newColor: string) => async () => {
//         console.log('click color', newColor);
//         await setColor(newColor);
//         update(newColor, getColor);
//     }
//     return (
//         <div style={{ color }}>
//             <b>{ color }</b> Choose a color &nbsp;
//             <button onClick={onClickColor('blue')}>blue</button>
//             <button onClick={onClickColor('red')}>red</button>
//             <button onClick={onClickColor('green')}>green</button>
//             <button onClick={onClickColor('pink')}>pink</button>
//         </div>
//     );
// }

</script>

// packages/example/src-isomor/color/color.tsx
import React from 'react';
import { useIsomor } from 'isomor-react';
import { getColor, setColor } from './server/color';

export const Color = () => {
    const { call, response: color, update } = useIsomor();
    const load = () => {
      call(getColor);
    }
    React.useEffect(() => { load(); }, []);
    const onClickColor = (newColor: string) => async () => {
        console.log('click color', newColor);
        await setColor(newColor);
        update(newColor, getColor);
    }
    return (
        <div style={{ color }}>
            <b>{ color }</b> Choose a color &nbsp;
            <button onClick={onClickColor('blue')}>blue</button>
            <button onClick={onClickColor('red')}>red</button>
            <button onClick={onClickColor('green')}>green</button>
            <button onClick={onClickColor('pink')}>pink</button>
        </div>
    );
}
