// packages/example/vue/src-isomor/components/error/ErrorExample2.vue
<template>
    <div>
        <p v-if="error" class="error"><b>Some error handling example 2:</b> {{error}} </p>
        <button @click="load()">Throw another error</button>
    </div>
</template>

<script lang="ts">
import {
  Component,
  Vue,
} from "vue-property-decorator";
import { getSomethingWithError } from "./server/data";
import { asyncCache, useAsyncCacheWatch } from "vue-async-cache";

@Component
export default class ErrorExample2 extends Vue {
  private cacheWatch = useAsyncCacheWatch(getSomethingWithError);

  get error() {
    return this.cacheWatch.getError();
  }

  load() {
    this.cacheWatch.load();
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.error {
  color: red;
}
</style>

// packages/example/react/src-isomor/error/ErrorExample2.tsx
import React from 'react';
import { useAsyncCacheWatch } from 'react-async-cache';

import { getSomethingWithError } from './server/data';

const errorStyle = {
  color: 'red',
}

export const ErrorExample2 = () => {
  const { load, response, error } = useAsyncCacheWatch(getSomethingWithError);
  return (
    <div style={errorStyle}>
      {error && <p><b>Some error handling example 2:</b> {error.toString()} </p>}
      <button onClick={load}>Throw another error</button>
    </div>
  );
}
